### PR TITLE
Fixes transpilation error

### LINKED ISSUE #761: Type 'DateType' does not satisfy the constraint
Type 'DateType' does not satisfy the constraint 'BasicDataNode'.ts(2344)
interface.d.ts(59, 25): This type parameter might need an `extends BasicDataNode` constraint.

`export type KeyEntities<DateType = any> = Record<SafeKey, DataEntity<DateType>>;`

https://github.com/react-component/tree/blob/9269acc8a869e3905f339ddc955d6bd8c6966646/src/interface.tsx#L72

### PR DESCRIPTION
**Pull request by jljouannic**
Fixes #761 (transpilation error on project using rc-tree (directly or not) with option `skipLibCheck` set to `false`)

### CODE REVIEW

**Comment by yoyo837** [comment]
CI failed.

**Comment by jljouannic** [comment]
> CI failed.

Yes, indeed, but not because of the content of this PR

**Comment by yoyo837** [comment]
Rebase please.

**Comment by jljouannic** [comment]
Rebase done

**Review by yoyo837 — APPROVED** [review]

**Pull request merged**
