### PR TITLE
fix(ts): fix NodeListProps type error in ts@4.8.2

### PR DESCRIPTION
**Pull request by phyng**
Type error when use typescript@4.8,2

Reproduce:

- open https://replit.com/@jnhy/rc-tree-test and click run, then type `npm start` then enter
- or clone https://github.com/phyng/rc-tree-test to local and run `npm install && npm start`

Before:
image

After:
image

### CODE REVIEW

**Comment by afc163** [comment]
如何重现问题？

**Comment by phyng** [comment]
@afc163 我补充了一个可以重现的示例 https://github.com/phyng/rc-tree-test 关键因素是 `"typescript": "4.8.2"` (这是 TypeScript 的最新版本)

克隆项目到本地运行下面命令就能重现：

```
npm install
npm start
```

**Comment by phyng** [comment]
补充一个 replit 的链接，可以在线重现，点击运行后输入 `npm start` 就能重现: https://replit.com/@jnhy/rc-tree-test

**Comment by afc163** [comment]
在 https://github.com/react-component/tree/blob/master/tests/type.spec.tsx 这里加个用例防止以后改挂吧。

**Comment by inglec-arista** [comment]
Any progress on this? Still blocked on upgrading to `typescript@4.8.x` until this is merged :)

**Comment by phyng** [comment]
后来被 https://github.com/react-component/tree/commit/e2da1ce6cdf62bb685254865364f3fec4ed56651 修复

**Pull request closed without merging**
