### PR TITLE
Don't update full treeview on individual element select / expand

### LINKED ISSUE #80: Tree.render() slow for large shallow trees
It seems that the way that rc-tree renders Tree makes minor updates (such as expanding or selecting a single node) very slow for large trees. This appears to be optimized in the case of deep trees (i.e. many elements hidden behind folders), but not for shallow trees (fewer elements, not hidden by folders).

A simple case be shown with the [big-data example](https://react-component.github.io/tree/examples/big-data.html). When using x=5, y=500, z=1, there are 1252505 total nodes, but selecting elements is still snappy. When using x=500, y=5, z=1, there are 15500 total nodes, but selecting elements can take up to a second to update.

This might be a no-fix, but it would be helpful for simple actions such as select or expand to only update the relevant nodes. Otherwise interacting with the tree starts feeling laggy above 500 nodes, which seems small compared to other frameworks' TreeViews...

### PR DESCRIPTION
**Pull request by naderm**
Fixes #80

### CODE REVIEW

**Comment by warmhug** [comment]
selected and expanded are not working.

**Comment by warmhug** [comment]
ref https://github.com/react-component/tree/issues/80#issuecomment-294427273

**Comment by benjycui** [comment]
@warmhug if you think this PR doesn't solve the problem, just close it.

**Comment by benjycui** [comment]
I am refactoring rc-tree, and will try to find other solution to solve the performance issue. But thanks anyway 😄

**Pull request closed without merging**
