### PR TITLE
Export `CheckInfo` interface

### LINKED ISSUE #411: should export interface CheckInfo ？
`onCheck?: (checked: { checked: Key[]; halfChecked: Key[] } | Key[], info: CheckInfo) => void;`

### PR DESCRIPTION
**Pull request by sklinov**
Exported `CheckInfo` interface.
For example, it is necessary for the `antd` `<Tree >` component's `onCheck` method.

Closes #411

### CODE REVIEW

**Comment by tsingson** [comment]
> Can we get this merged ?

i meet same issue in typescript.

**Comment by zifik** [comment]
*bump* 
Would be nice to have this out there.

**Comment by tubs-coder** [comment]
Not the same implementation, but CheckInfo is now accessible (https://github.com/react-component/tree/pull/757)

**Comment by yoyo837** [comment]
Rebase please.

**Comment by yoyo837** [comment]
Fixed in https://github.com/react-component/tree/pull/757.  Feel free to open a new PR for any problem.

**Pull request closed without merging**
