### PR TITLE
Ignore disabledCheck item

### PR DESCRIPTION
**Pull request by afc163**
close https://github.com/ant-design/ant-design/issues/6891

close https://github.com/react-component/tree/issues/99

### CODE REVIEW

**Comment by afc163** [comment]
@yesmeck 可能要和其他 PR 一起看看，我看到外面有好几个重量级的改动。

**Comment by wall0313** [comment]
Still need to consider the half checked situation. Like only if the checkbox is not disabled, sibling++. https://github.com/react-component/tree/blob/bc9ef1781a8976f100971d0770c3b34ca2efb2da/src/util.js#L211

Current in this PR:


It should be like:

**Comment by benjycui** [comment]
ping~ @afc163 , @wall0313 is right.

**Comment by benjycui** [comment]
ref: https://github.com/react-component/tree/issues/99

**Comment by afc163** [comment]
Fixed

**Comment by benjycui** [comment]
1.6.1

**Comment by afc163** [comment]
发现了一个问题，有点冲突了。

image

**Pull request merged**
